### ISSUE TITLE
jsr special page doesn't format properly

### ISSUE THREAD

**Issue by ksherlock** [mnaberez/m740dasm#1]
It displays as `jsr \{sp}`. Add an entry for `{sp}`/`sp_address` here:

https://github.com/mnaberez/m740dasm/blob/b2e29bdbb1763f33934027ef359e9077a4e8e8f5/m740dasm/listing.py#L115-L122

**Comment by mnaberez** [comment]
This should be fixed since 4fcb115ccbe65cdf25aaf7efc2d49ab299820067.  

Since I don't have a real firmware to test this with, we now [disassemble and reassemble](https://github.com/mnaberez/m740dasm/tree/bc6ac540381dc06522c18cb0f065fd224ba3a9a2/m740dasm/tests/end_to_end) a test file with it.
